name = "dev"
account_id = "70b41c5cd940670c3610e878a2fbac4e"
workers_dev = true
compatibility_date = "2025-03-28"

main = "workers-site/index.js"  # ⚠ site.entry-point hata diya hai

[site]
bucket = "./dist"

